wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: true
    python_version: 3.7.3
batch_size:
  desc: null
  value: 50
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.9
